### ISSUE TITLE
The Process of Diffusion Generation is Time Consuming

### ISSUE THREAD

**Issue by Scorpios1** [shiyegao/DDA#1]
Dear scholar, I'm interested in your excellent work, and want to reproduce this work. 
However, when I perform the Diffusion Generation, following your default parameters, but adjust the hyper-parameters of 'batch size' to 16 and 'num samples' to 50001, the speed of the generation is slow. I run the code for two days, and only generate 1w6 samples.
So I wonder how you overcome this point.

**Comment by shiyegao** [comment]
We used multiple GPUs to generate samples.  If you hope to do some experiments using only one GPU, it may be a good idea to use a part of the dataset, such as the top 5k images, instead of 50k.

Besides, improving the generation speed can also be considered. Recently, there are some fast sampling methods, like [DEIS](https://github.com/qsh-zh/deis)
 and [DPM-Solver](https://github.com/LuChengTHU/dpm-solver), which could be helpful.

We are also making progress in speeding up the generation in DDA, which will be released in the future.
