### ISSUE TITLE
Generated images sharing

### ISSUE THREAD

**Issue by dineshdaultani** [shiyegao/DDA#12]
Hi DDA authors,
Thanks for your great work. 
I am currently generating the adapted images using `image_adapt.sh` script. However, as you might know the generation process is very slow. It would take around `40+ days` on my current GPU environment just to generate `imagenet-c severity-5` images. 

Hence, I was thinking if it would be possible for you to share the DDA generated images using any platform like google drive/one drive? It would be really helpful and save a lot of computing resources. 

Please let me know about it. Will look forward to hearing from you. Thanks!

**Comment by shiyegao** [comment]
Thanks for your appreciation. Similar replies can be found in #1 and #6. 

We used multiple GPUs to generate samples. If you hope to do some experiments using only one GPU, it may be a good idea to use a part of the dataset, such as the top 500 or 5k images, instead of 50k.

Besides, improving the generation speed can also be considered.
